spring:
  # in-memory database for testing
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:


jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      format_sql: true
      show_sql: true
      use_sql_comments: true


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-doc